# Mandatory settings

blog_theme: dark # Or use dark
name: Devyong`s Blog
url: https://devyonghee.github.io
permalink: pretty

# Optional settings
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
utterances: devyonghee/devyonghee.github.io #Add your utterances repository
google_site_content: 1DbhSO778Ec8l_4qztuQgVDcPhc_ya64RGP-nwD_bj0 #Add your google site content
discus_identifier: # Add your Disqus identifier
ga_analytics: G-Q7PS3PZYZ6 # Add your GA Tracking Id
rss_enabled: true # Change to false if not
scrollappear_enabled: true # Change to false to disable
tag_nav_enabled: true # Change to true if you wish to show an additional 'tag-list' navigation below the header
theme_toggle: true # Change to true if you wish to show an icon in the navigation for dynamic theme toggling
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: https://github.com/devyonghee # Add your GitHub handle
  linkedin: # Add your LinkedIn handle
  twitter: # Add your Twitter handle
  email: devyonghee@gmail.com # Add your Email address
  bitcoin: # Add your Bitcoin link or address
  ethereum: # Add your Ethereum link or address
  gitlab: # Add your GitLab handle
  youtube: # Add your Youtube handle
  twitch: # Add your Twitch handle
  discord: # Add you Discord server invitation ID
  tumblr: # Add your Tumblr handle
  bitbucket: # Add your Bitbucket handle
  docker: # Add your Docker Hub handle
  instagram: # Add your Instagram handle
  keybase: # Add your Keybase handle
  medium: # Add your Medium handle
  spotify: # Add your Spotify handle
  stackoverflow: # Add your Stack Overflow ID number
  steam: # Add your Steam handle

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# Important settings (change at own risk)
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  collections:
    enabled: false
  categories:
    enabled: false
  tags:
    enabled: true
    layouts:
      - 'posts-tag.html'
    title: 'Posts with :tag'
    permalink: '/tag/:tag'
exclude:
  - src/*
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - README.md
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
