source "https://rubygems.org"

gem "html-proofer"
gem "jekyll", "~> 4.2.0"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jemoji"
gem "mini_magick"
gem "uglifier"
gem "jekyll-paginate-v2", "~> 3.0"
gem "jekyll-feed", "~> 0.15.1"
